config/routes.rb
Project2::Application.routes.draw do
  resources :appointments
    root :to => 'pages#home';
    get '/pages/project_2'
    get '/pages/calendar'

  

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]
  skip_before_filter  :verify_authenticity_token

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create 
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @appointment }
      else
        format.html { render action: 'new' }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:year, :month, :day, :time, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def project_2
  end
end


class PagesController < ApplicationController
  def calendar
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :month %><br>
    <%= f.number_field :month %>
  </div>
  <div class="field">
    <%= f.label :day %><br>
    <%= f.number_field :day %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<h1>Listing appointments</h1>

<table>
  <thead>
    <tr>
      <th width=70>Year     </th>
      <th width=70>Month     </th>
      <th width=50>Day     </th>
      <th width=70>Time     </th>
      <th width=200>Description     </th>
      <th width=35></th>
      <th width=40></th>
      <th width=40></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td align=center><%= appointment.year %>     </td>
        <td align=center><%= appointment.month %>     </td>
        <td align=center><%= appointment.day %>     </td>
        <td align=center><%= appointment.time %>     </td>
        <td align=center><%= appointment.description %>     </td>
        <td align=center><%= link_to 'Show', appointment %>     </td>
        <td align=center><%= link_to 'Edit', edit_appointment_path(appointment) %>     </td>
        <td align=center><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %>     </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<a onclick="location.href='/pages/calendar'">Go back to calendar</a>

app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @appointment.year %>
</p>

<p>
  <strong>Month:</strong>
  <%= @appointment.month %>
</p>

<p>
  <strong>Day:</strong>
  <%= @appointment.day %>
</p>

<p>
  <strong>Time:</strong>
  <%= @appointment.time %>
</p>

<p>
  <strong>Description:</strong>
  <%= @appointment.description %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/calendar.html.erb
<html>
<head>
    <title>            </title>
    <style type="text/css">
        table {
            border:           thin solid black;
  	    border-collapse:  collapse;
	}
        td, th {
            border: thin solid gray; 
        }    
	th.arrow{
            color: #9933FF;
    	}
	.currentmonth{
 	    text-align: left;
	}
	.currentday{
	    text-align: left;
	}
	.calendar td{
   	    padding: 2px;
	    width: 50px;
	}
	.currentmonth th{ 
 	    text-align: center;
	}
	.weekdays{
	    font-weight: bold; 
 	    text-align: center;
	}
</style>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js">
</script>
<script src="assets/javascripts/calendar.js">
</script>

</head>

<body>
    <h3>Group: Rafael Sanchez, Jianjun Li <br /> </h3>
    Time <br />
    <select id="time_t" name="Time">
        <option value="00:00">00:00</option>
        <option value="00:30">00:30</option>
        <option value="01:00">01:00</option>
        <option value="01:30">01:30</option>
        <option value="02:00">02:00</option>
        <option value="02:30">02:30</option>
        <option value="03:00">03:00</option>
        <option value="03:30">03:30</option>
        <option value="04:00">04:00</option>
        <option value="04:30">04:30</option>
        <option value="05:00">05:00</option>
        <option value="05:30">05:30</option>
        <option value="06:00">06:00</option>
        <option value="06:30">06:30</option>
        <option value="07:00">07:00</option>
        <option value="07:30">07:30</option>
        <option value="08:00">08:00</option>
        <option value="08:30">08:30</option>
        <option value="09:00">09:00</option>
        <option value="09:30">09:30</option>
        <option value="10:00">10:00</option>
        <option value="10:30">10:30</option>
        <option value="11:00">11:00</option>
        <option value="11:30">11:30</option>
        <option value="12:00">12:00</option>
        <option value="12:30">12:30</option>
        <option value="13:00">13:00</option>
        <option value="13:30">13:30</option>
        <option value="14:00">14:00</option>
        <option value="14:30">14:30</option>
        <option value="15:00">15:00</option>
        <option value="15:30">15:30</option>
        <option value="16:00">16:00</option>
        <option value="16:30">16:30</option>
        <option value="17:00">17:00</option>
        <option value="17:30">17:30</option>
        <option value="18:00">18:00</option>
        <option value="18:30">18:30</option>
        <option value="19:00">19:00</option>
        <option value="19:30">19:30</option>
        <option value="20:00">20:00</option>
        <option value="20:30">20:30</option>
        <option value="21:00">21:00</option>
        <option value="21:30">21:30</option>
        <option value="22:00">22:00</option>
        <option value="22:30">22:30</option>
        <option value="23:00">23:00</option>
        <option value="23:30">23:30</option>
    </select>
    <br /> <br /> Description <br />
    <input type="text" name="description" id="dt" value=""/>
    <br /> <br />
 
<body onload="calendar()">

<div id="calendar"></div>

<br />
<button type="button" onclick="location.href='/appointments'">Edit or Delete an Appointment</button>

<br /><br /><br />

</body>
</html>

app/views/pages/home.html.erb
<h1>Rafael Sanchez</h1>

<table>
	<thead>
		<tr>
			<th>Projects</th>
			<th>Description</th>
			<th>URL</th>
		</tr>
	</thead>
	<tbody>
		<% PROJECTS.each do |project, data| %>
			<tr>
				<td><%= project %></td>
				<td><%= data['description'] %></td>
				<td><%= link_to data['url'], data['url']%></td>
			</tr>
		<% end %>	
	</tbody>
</table>

app/views/pages/project_2.html.erb
<h2>Steps for Project 2</h2>
<p>
- added the gem 'bootstrap-sass' in the Gemfile
<br>
- ran the command "gem install twitter-bootstrap-rails"
<br>
- the file app/assets/javascripts/application.js is modified to add the bootstrap's javascript files
<br>
- in routes.rb, get '/pages/project_2' is added for a new web page
<br>
- in app/views/pages/home.html.erb, data['url'] is added next to link_to data to connect the url to the newly created webpage
<br>
- in config/environments/production.rb file, config.assets.compile is set to true in order to allow CSS on Heroku
</p>

app/views/pages/project_3.html.erb
<html>
<head>
    <title>            </title>
    <style type="text/css">
        table {
          border:           thin solid black;
  caption-side:     bottom;
  border-collapse:  collapse;
}
        td, th {
            border: thin solid gray;
            
            margin-right: 20px;
        }    
        button {
         color: gray;
            border: none;
            //background-color:transparent;
            font-weight:900;
        }
    button.button_arrow{
        color: darkblue;
    }
    button.button_current_day{
        color: black;
    }
    </style>
<style>
.premonth{
 color: gray;
 text-align: center;
}
.currentmonth{
 text-align: left;
}
.currentday{
 text-align: left;
}
.calendar td{
 padding: 2px;
 width: 50px;
}
.currentmonth th{ 
 text-align: center;
}
.weekdays{
font-weight: bold; 
 text-align: center;
}

</style>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js">
</script>
<script>
var count_year = 0;
var count_month = 0;
function calendar(){

var cal_argv = calendar.arguments;

//Variables to be used later.  Place holders right now.
var padding ="";
var totalFeb ="";
var i = 1;
var testing="";

 var current = new Date();
 var month = current.getMonth();
 var day = current.getDate();
 var year = current.getFullYear();


if (cal_argv[0] == 1) {
    count_year--;
}
if (cal_argv[0] == 2) {
    count_month--;
}
if (cal_argv[0] == 3) {
    count_month++;
}
if (cal_argv[0] == 4) {
    count_year++;
}

year += count_year;
if(month + count_month >11){
    
    if (  (((month+count_month)/12) >= 1)    ) {
        year+= Math.floor( (month+count_month)/12);        
    }
    
    month=((month+count_month)%12);
    

}
else if (month + count_month < 0) {
    
    if (  ( (month+count_month) < 0)    ) {
        year+= Math.floor( (month+count_month)/12);        
    }
    
    month=( 12-(  (Math.abs(month+count_month)) %12) )% 12;


}
 
else {
    month += count_month;

}

 //Determing if Feb has 28 or 29 days in it.  
 if (month == 1){
    if ( (year%100!=0) && (year%4==0) || (year%400==0)){
      totalFeb = 29;
    }else{
      totalFeb = 28;
    }
 }



//////////////////////////////////////////
// Setting up arrays for the name of     //
// the    months, days, and the number of    //
// days in the month.            //
//////////////////////////////////////////

 var monthNames = ["Jan","Feb","March","April","May","June","July","Aug","Sept","Oct","Nov", "Dec"];
 var dayNames = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday", "Saturday"];
 var totalDays = ["31", ""+totalFeb+"","31","30","31","30","31","31","30","31","30","31"]

//////////////////////////////////////////
// Temp values to get the number of days//
// in current month, and previous month.//
// Also getting the day of the week.    //
//////////////////////////////////////////

 var tempMonth = month+1; //+1; //Used to match up the current month with the correct start date.
 var prevMonth = month -1;



 var tempDate = new Date(tempMonth +' 1 ,'+year);
 var tempweekday= tempDate.getDay();
 var tempweekday2 = tempweekday
 var dayAmount = totalDays[month];
// var preAmount = totalDays[prevMonth] - tempweekday + 1;    
 
//////////////////////////////////////////////////
// After getting the first day of the week for    //
// the month, padding the other days for that    //
// week with the previous months days.  IE, if    //
// the first day of the week is on a Thursday,    //
// then this fills in Sun - Wed with the last    //
// months dates, counting down from the last    //
// day on Wed, until Sunday.            //
//////////////////////////////////////////////////

 while (tempweekday>0){
    padding += "<td class='premonth'></td>";
    //preAmount++;
     tempweekday--;
 }
//////////////////////////////////////////////////
// Filling in the calendar with the current     //
// month days in the correct location along.    //
//////////////////////////////////////////////////

 while (i <= dayAmount){

    //////////////////////////////////////////
    // Determining when to start a new row    //
    //////////////////////////////////////////

    if (tempweekday2 > 6){
        tempweekday2 = 0;
        padding += "</tr><tr>";
    }

    //////////////////////////////////////////////////////////////////////////////////////////////////
    // checking to see if i is equal to the current day, if so then we are making the color of    //
    //that cell a different color using CSS.  Also adding a rollover effect to highlight the     //
    //day the user rolls over. This loop creates the acutal calendar that is displayed.        //
    //////////////////////////////////////////////////////////////////////////////////////////////////

    if (  (i == day) && (month == current.getMonth() ) && (year == current.getFullYear())  ){
        padding +="<td height='50' class='currentday' bgcolor=\"#d9d9d9\" onMouseOver='this.style.background=\"#989898\"; this.style.color=\"#000000\"' onMouseOut='this.style.background=\"#D9D9D9\"; this.style.color=\"#000000\"'><button id=\"btn"+i+"\" class=\"button_current_day\"  onclick =\"addRow("+i+")\">"+i+"</button><ol id=\"ol_"+i+"\"></ol></td>";
    }else{
        padding +="<td height='50' class='currentmonth' onMouseOver='this.style.background=\"#989898\"' onMouseOut='this.style.background=\"#FFFFFF\"'><button id=\"btn"+i+"\" onclick=\"addRow("+i+")\">"+i+"</button><ol id=\"ol_"+i+"\"></ol></td>";    

    }
    
    tempweekday2++;
    i++;
 }


 /////////////////////////////////////////
 // Ouptputing the calendar onto the    //
 // site.  Also, putting in the month    //
 // name and days of the week.        //
 /////////////////////////////////////////

 var calendarTable = "<table class='calendar' width='995'> <tr class='currentmonth'><th button onclick='calendar(1)'> &#60&#60 </th><th button onclick='calendar(1)'> &#60 </th><th button onclick='calendar(2)' colspan='3' height='30'>"+monthNames[month]+" "+ year +"</th><th button onclick='calendar(3)'> &#62 </th><th button onclick='calendar(4)'> &#62&#62 </th></tr>";
 calendarTable +="<tr class='weekdays'>  <td height='30'>Sun</td>  <td>Mon</td> <td>Tues</td> <td>Wed</td> <td>Thurs</td> <td>Fri</td> <td>Sat</td> </tr>";
 calendarTable += "<tr height='50'>";
 calendarTable += padding;
 calendarTable += "</tr></table>";
 document.getElementById("calendar").innerHTML=calendarTable;

}

$('#orderform').submit(function() {
    if($('#dt').val() == ''){
        alert('Please fill out a description.');
        return false;
    }
});


function addRow(list_number){
    if(!dt.value==""){
        $("#ol_"+list_number).append(time_t.value +" "+ dt.value);
        dt.value="";
        time_t.value="00:00";
    }else{
        alert("Missing Description Field");
    }
}
</script>
</head>

<body>
    Time <br />
    <select id="time_t" name="Time">
        <option value="00:00">00:00</option>
        <option value="00:30">00:30</option>
        <option value="01:00">01:00</option>
        <option value="01:30">01:30</option>
        <option value="02:00">02:00</option>
        <option value="02:30">02:30</option>
        <option value="03:00">03:00</option>
        <option value="03:30">03:30</option>
        <option value="04:00">04:00</option>
        <option value="04:30">04:30</option>
        <option value="05:00">05:00</option>
        <option value="05:30">05:30</option>
        <option value="06:00">06:00</option>
        <option value="06:30">06:30</option>
        <option value="07:00">07:00</option>
        <option value="07:30">07:30</option>
        <option value="08:00">08:00</option>
        <option value="08:30">08:30</option>
        <option value="09:00">09:00</option>
        <option value="09:30">09:30</option>
        <option value="10:00">10:00</option>
        <option value="10:30">10:30</option>
        <option value="11:00">11:00</option>
        <option value="11:30">11:30</option>
        <option value="12:00">12:00</option>
        <option value="12:30">12:30</option>
        <option value="13:00">13:00</option>
        <option value="13:30">13:30</option>
        <option value="14:00">14:00</option>
        <option value="14:30">14:30</option>
        <option value="15:00">15:00</option>
        <option value="15:30">15:30</option>
        <option value="16:00">16:00</option>
        <option value="16:30">16:30</option>
        <option value="17:00">17:00</option>
        <option value="17:30">17:30</option>
        <option value="18:00">18:00</option>
        <option value="18:30">18:30</option>
        <option value="19:00">19:00</option>
        <option value="19:30">19:30</option>
        <option value="20:00">20:00</option>
        <option value="20:30">20:30</option>
        <option value="21:00">21:00</option>
        <option value="21:30">21:30</option>
        <option value="22:00">22:00</option>
        <option value="22:30">22:30</option>
        <option value="23:00">23:00</option>
        <option value="23:30">23:30</option>
    </select>
    <br /> <br /> Description <br />
    <input type="text" name="description" id="dt" value=""/>
    <br /> <br />
 
<body onload="calendar()">

<div id="calendar"></div>

</body>
</html>